---
- name: Configure backend servers
  hosts: backend
  become: yes
  tasks:
    - name: Add Netdata repository
      apt_repository:
        repo: "deb [arch=amd64] https://repo.netdata.cloud/repos/stable/debian/ bullseye main"
        state: present
        filename: netdata
        update_cache: yes
      when: ansible_distribution == "Debian"
      
    - name: Install Netdata
      package:
        name: netdata
        state: present
        
    - name: Ensure Netdata is running
      service:
        name: netdata
        state: started
        enabled: yes
