---
- name: Common configuration for all Linux servers
  hosts: all
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
      when: ansible_distribution == "RedHat"
      
    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_distribution == "RedHat"
      
    - name: Stop and disable ufw (for Debian)
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_distribution == "Debian"
